### ISSUE TITLE
Missing expected inferences on frontier-less rule with an IDB atom in the body

### ISSUE THREAD

**Issue by mmarx** [karmaresearch/vlog#43]
This is a reduced version of the problem demonstrated by knowsys/rulewerk#166.

Consider the following `edb.conf`:
```
EDB0_predname=bb
EDB0_type=INMEMORY
EDB0_param0=.
EDB0_param1=bb
EDB1_predname=c2
EDB1_type=INMEMORY
EDB1_param0=.
EDB1_param1=c2
```

with `bb.csv` containing
```
star
```
and `c2.csv` containing
```
cy
```
(i.e., both EDB predicates have a single constant fact).

Then the following rules
```
b(X) :- bb(X)
rel(r0) :- c2(cy),b(X)
```
do not derive `rel(r0)` (even though it clearly follows from the program and the facts).

Note that
```
b(X) :- bb(X)
rel(r0) :- c2(cy),bb(X)
```
successfully derives `rel(r0)`, as does
```
b(X) :- bb(X)
rel(r0) :- b(X)
```
and that
```
b(X) :- bb(X)
rel(X) :- c2(cy),bb(X)
```
derives `rel(star)`.

All these examples have been run on the current master, `chase-benchmarking-540-g1b5dbdb` as per `git describe`.

**Comment by mrnolte** [comment]
Hey there,
For my master thesis I have to evaluate an algorithm based on Datalog entailment. Due to this bug, my implementation returns wrong results. I consider if it makes sense to do the experiments anyway or if I should better wait for a fix. Both options are perfectly fine, but if there is little time for you to take a look at the bug in the near future, I'd go with the first one. What's your opinion on this? :)
Cheers,
Robin
