### ISSUE TITLE
Wrong RMFA (and RMSA) classification

### ISSUE THREAD

**Issue by CerielJacobs** [karmaresearch/vlog#78]
With rules

P(Y,Z) :- P(X,Y)

and empty edb.conf, the command

vlog cycles --alg RMFA --rules rules -e edb.conf

classifies this rule-set as RMFA, but it is not.

Explanation (by @irina-dragoste):
1. we have to check if substitution [x/c, y/c] is blocked. For this, it suffices to check whether [x/c1, y/c2] is specifically-blocked, for c1 and c2 some fresh constants (Lemmas 14 and 15). As there are no Datalog rules, this is equivalent to checking if P(c1,c2) entails Exists z . P(c2,!z) (See Definition 13). As this is not true, fact P(c ,f(c)) is added to RMFA(R).
2. then, we have to check if the substitution [x/c, y/f(c)] is blocked, which implies checking that [x/c1, y/f(c2)] is specifically-blocked. This is equivalent to checking whether {P(f(c2),c1), P(c3,c2), P(c2,f(c2))} entails Exists z. P(f(c2),!z), for c3 a fresh constant. As this is not true, cyclic fact P(f(c),f(f(c))) is added to RMFA(R) and the rule set is not RMFA.

**Comment by irina-dragoste** [comment]
What is the critical instance in this case? If it is constructed from all predicates that appear in the ruleset, regardless of the edb.conf, why is the edb.conf relevant here?

**Comment by CerielJacobs** [comment]
It is not relevant, but the command-line vlog requires an edb.conf.

**Comment by irina-dragoste** [comment]
Because the paper does not discuss directly how to implement a blocking check, but treats it theoretically, I detailed it in this example here.

![image](https://user-images.githubusercontent.com/26414082/132542710-8852e92b-73b2-405b-a94f-fc10a5a5d7d4.png)
![image](https://user-images.githubusercontent.com/26414082/132542827-91174013-f3b1-44dd-9673-c3a06804a12a.png)
![image](https://user-images.githubusercontent.com/26414082/132542882-f9eb0cdb-c192-4322-af45-f7796eee4db8.png)
